### ISSUE TITLE
Scheduled auto revalidation & report using recorded web discovery

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#106]
### Write a Quartz job  that :
- forks an env, using an EnvironmentService extracted from refactoring EnvironmentActionsBean
- replays an exchange record (of a web discovery) by calling (sync) ReplayEngine(Impl).replay()
- (which has to be set up in a frascati sca app - see below, and its interface extracted in api)
- renders the validation rest service towards a simple static html report, and put it in Nuxeo in the env with a name including the date
- Set it up in Nuxeo's Quartz, make it configurable : scheduling pattern, name / path / ref / id of the env to refork, name / path / ref / id of the web discovery record to replay
### Write a (ExchangeRecord) Servlet filter that :
- after filtering calls a java FraSCAti Service in Nuxeo
- on its method handleExchange(HttpServletRequest, HttpServletResponse)
- which has to be implemented on top of the Record / Template & assert generation mechanism
- which has to be made pluggable using a ComposedExchangeHandler with a multiple "exchangeHandlers" Reference
- (refactor the httpmonit proxy etc. if required)
- setup a dedicated frascati sca & maven app "webdiscoveryhttpminer" that assembles & provides ExchangeRecordServletFilter & ReplayEngineImpl
- the current run manager has to be improved to allow to create (= name), start & stop runs through a user-friendly GUI
### Start this as EasySOA FraSCAti SCA app :

Build on : deployment api, deployable model prototype, f in n ; to allow : prototype of EasySOA-managed server / model / api (& fstudio integration api), "easysoa by easysoa".

While doing the following, try to keep apis in an api project & decoupled from nuxeo (ex. EnvironmentManager), and if impossible to underline why. This way it'll be more interesting vs integrating FStudio, Talend etc.

Complete AppImpl model :
- FraSCAtiAppImpl.manager = EasySOA(or EmbeddedFraSCAti)AppImplManagerService (deployer = MavenDeployerService)
  MavenArtifactDeployerAppImpl.mavenids (multivalued prop) = ...httpminerwebdiscovery => deployables.deployable { deployableMavenId, (deployableLocalFilePath), deployableClasspathId, deployableVersion }
- add appimpl instance for webdiscoveryhttpminer in master env in default registry setup => content template contribution

Write a new EasySOA(or EmbeddedFraSCAti)AppImplManager nuxeo service whose deployAndStart() :
- deploy() : (download and copy artifact at LOCAL_DEPLOY_PATH or) do nothing, only check it is already there
- start() : NxFraSCAtiService.start(artifact) (i.e. processComposite)
- & idem stop

Write a new EnvironmentManager nuxeo service that hooks on onNuxeoStart event to :
- for each env, for each app, app.manager.deployAndStart();
- & idem stop
- LATER refresh, handle "deploying/starting/..." state

**Comment by mkalam-alami** [comment]
### Current state

**Architecture**
- OK Finish servlet filter `easysoa-proxy-core-webdiscoveryhttpminer` and integrate it
- OK Make FraSCAti in Nuxeo work
- OK Check that it's possible to use a Nuxeo service from an isolated FraSCAti app

**Features**
- OK Command the servlet filter from the Run Manager FraSCAti app
  - (interface: start/stop/callback to call on every request)
- OK Command the Replay service from Nuxeo
  - (interface: synchronous request of a run replay, with each request adapted for a specific environment)

**Polishing**
- OK Make Run Manager UI nicer (for 0.4 release)
- OK Elaborate demo scenario (idem)

**Comment by mkalam-alami** [comment]
Everything is implemented, closing
