### ISSUE TITLE
Fix remaining issues after Nuxeo 5.5 alignment

### ISSUE THREAD

**Issue by mkalam-alami** [easysoa/EasySOA#111]
On this issue will be listed all unresolved problems following the Nuxeo 5.5 alignment.
## Tests (?)

Here at Open Wide we had troubles running any Nuxeo-related tests after the update ; for instance the **DocumentServiceTest** from **easysoa-registry-core** didn't want to launch because it couldn't find the bundle "org.easysoa.registry.core" (see @Deploy annotation in **EasySOACoreTestFeature**).

As of today I can't reproduce this, but it would be nice if someone at Nuxeo checked our way to set up tests with annotations, which is probably incorrect in some way.
### File download/parsing thread

Not a big deal, but within tests, the thread held by **WebFileParsingPoolServiceImpl** currently leads to "leaked sessions". I tried to ensure the core session is closed upon component deactivation, but it didn't change a thing.

```
ERROR [CoreFeature] There are 1 open session(s) at tear down; it seems the test leaked 1 session(s).
WARN [CoreFeature] Leaking session
org.nuxeo.ecm.core.api.CoreInstance$RegistrationInfo: Session registration context (test-4249383738640695304,WebFileParsingPoolService)
    at org.nuxeo.ecm.core.api.CoreInstance.registerSession(CoreInstance.java:158)
    at org.nuxeo.ecm.core.api.AbstractSession.connect(AbstractSession.java:206)
    at org.nuxeo.ecm.core.api.repository.Repository.open(Repository.java:155)
    at org.nuxeo.ecm.core.api.repository.Repository.open(Repository.java:113)
    at org.easysoa.services.webparsing.WebFileParsingPoolServiceImpl.run(WebFileParsingPoolServiceImpl.java:164)
    at java.lang.Thread.run(Thread.java:662)
```
## Workspace layout

When browsing a workspace:
- We can't view the workspace's metadata anymore in the default view.

**Comment by tiry** [comment]
For the tests, I can not reproduce your issue.
Althought, I have failed tests, there is no issues in deploying "org.easysoa.registry.core".
Did you experience this in maven / command line ?
(Looks to me like a broken eclipse issue).

Anyway, I'll try to see if I can fix the failing tests.
For the leaking core session , the tests only need to cleanup the session during the tearDown.

**Comment by mkalam-alami** [comment]
Thanks for your answer. Indeed now that you mention it the bundle issues are probably related to Eclipse. The tests now "work" like they used to before the update.

The only remaining issue is the invisible workspace metadata problem (the view tab doesn't display any metadata nor the EasySOA icons, only the documents it contains).

**Comment by tiry** [comment]
I'll fix that soon ;)
Le 27 mars 2012 12:26, "Marwane Kalam-Alami" <
reply@reply.github.com>
a crit :

**Comment by tiry** [comment]
https://github.com/easysoa/EasySOA/commit/ac53ff10dfb170b52f90f9d072b3353e8e785f9a
Tell me if this is ok for you and if this solves the missing view.

**Comment by mkalam-alami** [comment]
Indeed the workspace "Contents" section now appears, thanks. It's not exactly like it's supposed to be yet, but I think I can finish fixing this, I'll keep you in touch.

**Comment by tiry** [comment]
Should we close this issue ?

**Comment by mkalam-alami** [comment]
Yep it's all good.
