### ISSUE TITLE
Make a 0.4 demo release

### ISSUE THREAD

**Issue by mkalam-alami** [easysoa/EasySOA#117]
All done

**Comment by JGuillemotte** [comment]
Scaffolder proxy now works in embedded Nuxeo FraSCAti.

For the smart travel sample, there is still a problem with FraSCAti and the mocked services param names. For the release, we have to use the standalone CXF version started outside the Nuxeo FraSCAti.

**Comment by JGuillemotte** [comment]
Main problems in the release 0.4 :
- There is a problem with the EasySOA Light summary page with some browsers. All work fine with the browser rekonq but with Konqueror, the Scaffolded service clients list is never displayed
- Service registry : linked services from the "Service discovery by browsing" page are well registered in Nuxeo but the "notifed by browsing" icon is not activated (same problem for all registered services). In addtion, the button call it is never activated.
- Scaffolding proxy : nothing to report with easysoa sample services (airport information service and smart travel trip), work fine. Make a try with another service (http://www.webservicex.net/whois.asmx) registered from the "Some handy web services" in "Service discovery by browsing" page. There is a problem with this service, the html form is generated without problems but when a request is send to the service, a soapui error is throwed :

[LOG INTENT]  Arg Object type : org.eclipse.jetty.server.Request, Object value : (GET /callService/whoisSoap/GetWhoIS/?callback=jQuery164025562836532481015_1341407957099&request=%7B%22wsRequest%22:%20%7B%20%22service%22:%20%22whois%22,%20%22binding%22:%20%22whoisSoap%22,%20%22operation%22:%20%22GetWhoIS%22,%20%22wsdlUrl%22:%20%22http://www.webservicex.net/whois.asmx?wsdl%22%7D,%22formParameters%22:%5B%7B%22paramName%22:%22HostName%22,%22paramValue%22:%22google.com%22%7D%5D%7D&_=1341407973183)@29091418 org.eclipse.jetty.server.Request@1bbe65a
[AUTOREARMFUSE INTENT] Current time (Ms) : 1341407973190
[AUTOREARMFUSE INTENT] Requests in queue : 6
[AUTOREARMFUSE INTENT] Older request time in queue : 1341407780905
[LOG INTENT] PUT LOG INTENT CODE TO RUN BEFORE THE JOINPOINT PROCESSING
[LOG INTENT]  Arg Object type : org.eclipse.jetty.server.Request, Object value : (GET /callService/whoisSoap/GetWhoIS/?callback=jQuery164025562836532481015_1341407957099&request=%7B%22wsRequest%22:%20%7B%20%22service%22:%20%22whois%22,%20%22binding%22:%20%22whoisSoap%22,%20%22operation%22:%20%22GetWhoIS%22,%20%22wsdlUrl%22:%20%22http://www.webservicex.net/whois.asmx?wsdl%22%7D,%22formParameters%22:%5B%7B%22paramName%22:%22HostName%22,%22paramValue%22:%22google.com%22%7D%5D%7D&_=1341407973183)@29091418 org.eclipse.jetty.server.Request@1bbe65a
[AUTOREARMFUSE INTENT] Current time (Ms) : 1341407973191
[AUTOREARMFUSE INTENT] Requests in queue : 7
[AUTOREARMFUSE INTENT] Older request time in queue : 1341407780905
[LOG INTENT] PUT LOG INTENT CODE TO RUN BEFORE THE JOINPOINT PROCESSING
[LOG INTENT]  Arg Object type : java.lang.String, Object value : http://www.webservicex.net/whois.asmx?wsdl
[LOG INTENT]  Arg Object type : java.lang.String, Object value : whoisSoap
[LOG INTENT]  Arg Object type : java.lang.String, Object value : GetWhoIS
[LOG INTENT]  Arg Object type : java.util.HashMap, Object value : {HostName=[google.com]}
Progress: 1 - Caching Definition from url [http://www.webservicex.net/whois.asmx?wsdl]
Progress: 2 - Loading [http://www.webservicex.net/whois.asmx?wsdl]
15:19:33,192 DEBUG [WsdlLoader] Getting wsdl component from [http://www.webservicex.net/whois.asmx?wsdl]
15:19:36,398 ERROR [SoapUI] An error occured [com.eviware.soapui.impl.support.definition.support.InvalidDefinitionException], see error log for details
com.eviware.soapui.impl.support.definition.support.InvalidDefinitionException
    at com.eviware.soapui.impl.wsdl.support.wsdl.WsdlLoader.loadXmlObject(WsdlLoader.java:122)
    at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.getDefinitionParts(SchemaUtils.java:532)
    at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.getDefinitionParts(SchemaUtils.java:521)
    at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionCache.update(AbstractDefinitionCache.java:97)
    at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionContext$Loader.construct(AbstractDefinitionContext.java:226)
    at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:46)
    at com.eviware.soapui.support.swing.SwingWorker$2.run(SwingWorker.java:149)
    at java.lang.Thread.run(Thread.java:662)
com.eviware.soapui.impl.support.definition.support.InvalidDefinitionException
    at com.eviware.soapui.impl.wsdl.support.wsdl.WsdlLoader.loadXmlObject(WsdlLoader.java:122)
    at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.getDefinitionParts(SchemaUtils.java:532)
    at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.getDefinitionParts(SchemaUtils.java:521)
    at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionCache.update(AbstractDefinitionCache.java:97)
    at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionContext$Loader.construct(AbstractDefinitionContext.java:226)
    at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:46)
    at com.eviware.soapui.support.swing.SwingWorker$2.run(SwingWorker.java:149)
    at java.lang.Thread.run(Thread.java:662)
- Run manager and Replay manager : There is a problem with the property manager. Properties are not well loaded so the path used define folders for exchange record stores are set to null. As a consequence, the run manager save the runs directly under the serviceRegistry folder and the replay manager cannot retrieve the stored run list. Seem's to be a singleton problem. The PropertyManager is well initialized with the property file but when the method the get the PropertyManager is called, the property manager doesn't contains the right property values.

**Comment by mkalam-alami** [comment]
> - There is a problem with the EasySOA Light summary page with some browsers. All work fine with the browser rekonq but with Konqueror, the Scaffolded service clients list is never displayed
> - Service registry : linked services from the "Service discovery by browsing" page are well registered in Nuxeo but the "notifed by browsing" icon is not activated (same problem for all registered services). In addtion, the button call it is never activated.

Both problems are fixed now (with ddd1184bdd7c and dc927b2d).

I just updated the issue to mention the other ones.

**Comment by mkalam-alami** [comment]
Release ready, closing
