### ISSUE TITLE
Change tabs to 4 spaces + add copyright notices

### ISSUE THREAD

**Issue by sfermigier** [easysoa/EasySOA#13]

**Comment by mdutoo** [comment]
Thanks Stéfane - though we said 3 spaces yesterday ;)

We plan that along with more cleaning (package names...) for the first official release in september.

**Comment by mdutoo** [comment]
Coding conventions and lIcensing handled, see https://github.com/easysoa/EasySOA/wiki/Coding-conventions

Old code is updated to coding conventions step-by-step at each opportunity, rather than big bang-style.
