### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by andreas20** [easysoa/EasySOA#139]
EasySOA Registry (8080)
Discovery by Browsing (8083)
This might be a silly question but i did not find any clarification anywhere. When I initialize the above, everything is French, is there a translation file or language option for English? Please explain.

Thank you.

**Comment by mdutoo** [comment]
Hi Andreas20

I've done a quick check. So : 
- the model & document management part of EasySOA Registry is well translated in English and French, at http://localhost:8080/nuxeo
- the home, service browsing and indicators part of EasySOA Registry is well translated, BUT translation files were wrongly named. I've just patched that in EasySOA-Incubation : 
  https://github.com/easysoa/EasySOA-Incubation/commit/ad598c9de29f80eccd49dab3d34e033fb7d1b728
- the Discovery by Browsing had not yet been internationalized (though translations exist as comments within HTML). I'd checked that the i18next js library could address this problem and will do it by next week.

Thanks for the inquiry.

**Comment by mdutoo** [comment]
As can been seen in last commits,
- the Discovery by Browsing UI has been internationalized using i18next.js : Backbone.js app, iframe, bookmarklet, examples. Those new translation files are at https://github.com/easysoa/EasySOA-Incubation/tree/master/easysoa-discovery-browsing/www/locales
- the Service Documentation part of the Service Browsing UI of EasySOA Registry had NOT been translated yet, so I've just done that. Enriched translation files are at https://github.com/easysoa/EasySOA-Incubation/tree/master/easysoa-registry-v1/easysoa-registry-rest-server/src/main/resources/i18n

I plan to do a new release someday, until then you can build it on your own as described in the wiki.

**Comment by andreas20** [comment]
Hi thank you for your replies but certain things I didnt get.
The http://localhost:8080/nuxeo I can see that is in English and its ok. But for <Discovery by Browsing> and <EasySOA Proxy>, how can I add the translation files above? Also you are referencing EasySOA v1, isnt there a v2? 

Thank you, Andreas.
