### ISSUE TITLE
Refactor scaffolder proxies toward a generic one

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#34]
(initially in https://github.com/easysoa/easysoa-model-demo/issues/29 )

**Comment by mdutoo** [comment]
Result 
:
- Done by jguillemotte
- Used SOAPUI as (pluggable) impl of generating SOAP requests, to try working with it
- Generating a generic HTML form from WSDL works well for simple WSDLs (with only primitive parameters).

Next step
- In the case of WSDLs with a complex data tree, since such a generic form becomes merely unusable, we advise first reducing data structure complexity in a business layer by a custom transformation proxy (using request and response templates and data field mappings written in XSL, velocity, mustache.js ; or even server script code, Talend jobs)
- the other part of a two-tier Light architecture, aka the presentation layer, can be done by a proxy using either presentation templates or a form engine supporting typed data.
- then we won't be far away from a wizard engine, or even a workflow engine.

**Comment by JGuillemotte** [comment]
See object-model based HTML generation in https://github.com/easysoa/easysoa-model-demo/issues/34
