### ISSUE TITLE
Make existing demo scenarii collaborative

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#36]
By reworking existing demo scenarii with one different user for each profile.

Also adapt features & profiles so demos work out best (ex. each profile has a different preffered virtual navigation tree).
Involves removing hardcoded Administrator user (easy) & credentials (not so, see question to Nuxeo about BASIC auth, possibly keep same password for now).

LATER :

Evaluate which Nuxeo collaborative features can be easily adapted for EasySOA. Ask Nuxeo about that and about how we share the work.

Ideas, from easiest to hardest :
- SOA documentation : generate trees of notes or of wiki pages or of documentation folder along service trees, SOA document approval workflow...
- topic-based communication (posts ex. forum ; notification ex. messages, twitter), where what's said on a business application also trickles down to services it uses and those who expose them, and vice versa
- project management features, like workplaces : ex. using Redmine (see OWO & Easifab http://easifab.com/index.php/outils-a-technlogies )
- service lifecycle management & workflow (with EasiFab, requires Integration-side Feature)
- dev / soa project management features, like tasks integrated with JIRA (mylyn) / bugtracker / agile (scrum backlog http://stackoverflow.com/questions/1459325/redmine-and-scrum ), see Easifab http://easifab.com/index.php/easifab/concepts

**Comment by mkalam-alami** [comment]
Done for 0.3:
- Enabled user profiles and authentication everywhere
- Various collaborative features including comments, document history, document annotations, (buggy) workflows

For the next goals, see #56
