### ISSUE TITLE
Discovery By Browsing UI problems when resizing

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#39]
TO BE Q/A TESTED FOR EACH RELEASE, MOVE IT TO THE NEXT RELEASE rather than closing it once a release is out.

typically happens when doing a demo on an external screen.
- content of "browser within a browser" iframe disappears when width is ~800

How to solve them : open firebug in firefox, there select the problematic part of the web page, then work on its css attributes on the bottom right (by disabling one line at a time, changing values or px to %...)

**Comment by mdutoo** [comment]
Solved "content of iframe disappears when resizing" by putting #iframeContainer's margin-left from 21px to 2% . Then had to change a few others (borders done another way...) to get the same result.

**Comment by mkalam-alami** [comment]
Adjusted so that "Save" button never disappears
