### ISSUE TITLE
in release, paf services don't work without internet

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#40]
It fails on startup because it can't load the remote file http://www.springframework.org/schema/beans/spring-beans.xsd which is required in the "cxf.xml" configuration file at the root of its single jar packaging.

However it works well when starting it using junit test starter in Eclipse.

The cause is very probably that the single jar packaging is made out of multiple jars, which for instance may have overriden a few files with the same name from, including a locally available spring-beans.xsd, my hunch being on the path META-INF/schemas/beans.xsd .

TODO go back to previous studies of possible packaging methods, update it, choose another method and apply it to paf services.

**Comment by JGuillemotte** [comment]
Packaging changed. Now a zip archive is generated by the command mvn assembly:assembly. In this zip, there is 2 scripts (sh and bat) to launch the PAF server, a bin folder with the main jar and lib folder containing all the required jar libraries.

**Comment by JGuillemotte** [comment]
TODO MKA integrate new packaging in the release

**Comment by mkalam-alami** [comment]
Integration done: https://github.com/easysoa/EasySOA/commit/9b6e95da9fbb606084afd729a5580d0183e81e73
