### ISSUE TITLE
paf proxy port conflict

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#41]
When starting everything in a setup similar to 0.3 release (everything from 0.2 release, except scaffoldingProxy & paf server using junit test starters within Eclipse, and also registry & web), paf proxy fails to start.

However, it starts OK when moving its port from 7001 to 7051 in its SCA composite (and in the html that links to it).

TODO reproduce, see with which port it conflicts, solve it and enrich the wiki page (https://github.com/easysoa/EasySOA/wiki/Used-ports) listing all ports being in use.

**Comment by JGuillemotte** [comment]
The problem occurs when the scaffolding proxy and the registry are launched in the same time in test mode. The scaffolding proxy use the port 7001 to publish the Rest/Soap proxy and the Registry launch a Rest/Soap server on the same port just for tests.

See .../easysoa/easysoa-registry/easysoa-registry-core/src/test/resources/org/easysoa/sca/RestSoapProxy.composite

Hum ... This is not the good reason. The composite in registry-core is not used to start a FraSCAti engine.

It seems that an old module : easysoa-samples-paf-restsoapproxy has been launched at the same time that the new scaffolding proxy. This old paf sample module uses the port 7001 so it can explain the conflict.

The project easysoa-samples-paf-restsoapproxy is now obsolete and will be deleted !
