### ISSUE TITLE
Integrate scaffoldingProxy-based Airport sample in web and release

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#42]
this implies :
- 1. **DONE**: MDU in registry-core's ServiceListener, hook its URL http://localhost:8090/scaffoldingProxy/?wsdlUrl=http://localhost:8200/esb/AirportService?wsdl (rather than something like http://localhost:8090/scaffoldingProxy/?wsdlUrl=http://localhost:8200/esb/AirportService?wsdl)
- 2. **DONE**: make it work in tests - patch bugs :
  - 2.1 if no /definitions/@name use rather the last segment of /service/port/address/@location (ex. AirportService) for web page title & header
  - 2.2 airport wsdl hack : inverse the names of airport_soap.wsdl and server_airport_soap.wsdl, so airport_soap.wsdl is the original one and the same as the one provided in the Talend airport sample, and talk about it in the scaffoldingProxy's readme
  - 2.3 airport wsdl hack : replace absolute filesystem URLs by relative ones, and (for instance) put in FormGenerator code that adds the absolute part by taking it from sys prop "user.dir"
- 3. **DONE** **SEE #44**: make it work in tests - integrate web layout, and especially web resources served by node.js (Light50.png & style.css), by :
  - 3.1 MKA use node.js / connect / express to proxy the scaffoldingProxy, so relative URLs to node-served resources are possible . NB. it will also work in test-started scaffoldingProxy AT THE CONDITION it is accessed through node, which is acceptable for Q/A testing (while unit testing doesn't need pretty layout)
- 4. **DONE**: make it work in the release - package both in (as frascati app on the same port, with all wsdls and contents in its jar)
- 5. **DONE**: add esper proxy
- 6. **DONE**: do the same for other samples (paf, smartTravel) : replace static HTML (form.html) by URLs to scaffoldingProxy-generated HTML

**Comment by mdutoo** [comment]
done 1.

**Comment by JGuillemotte** [comment]
2.1 : done
2.2 : done
2.3 : done

**Comment by mkalam-alami** [comment]
1. : done, by conf'ing SOAPUI libs so they use it as proxy (rather than by adding to .bat/sh set CUSTOM_JAVA_OPTS=-Dcxf.config.file=cxfEsperProxy.xml)
